### PR TITLE
add some topic modeling analysis

### PR DESCRIPTION
**Pull request by Fredus14**
Hi Sergiusz, I've added the code and some visualisation output of Hillary's  emails topic modelling analysis.

### CODE REVIEW

**Comment by YvesCR** [comment]
Hello Fabio, you did a fine piece of code.

The previous session , we had created a website for the coding dojo. With
rstudio and rmarkdown, it is really easy to wrap any r code in a rmarkdown
script and to create an html output format.


The idea is not to create perfect article, just to publish the work done in
a few hours. So no worries if it is messy :)

Would you be ok to play the game and publish the code in an article format?
Your github profile will be linked to the article.

You could find the concept here:
https://london-r-dojo.github.io/2016/01/rmarkdown-intro-coding-dojo.html

If you are ok, all I ask you is to include your code in a .rmd script and
to knit the output in html ( or just in the rmd format, it is fine).
Then I'll be able to put in the website. (even if you are enthusiast, you
could do it yourself, but this part may be complicated the first time).

If you don't have time, it is fine.

Thanks,

Yves


2016-02-14 13:06 GMT+00:00 Fabio Amaral <notifications@github.com>:

**Comment by Fredus14** [comment]
Hello Yves,

No problem, It was fun working on this dataset.
I was already preparing an markdown document for this analysis and I will share it soon.

Cheers

Fabio

**Comment by YvesCR** [comment]
Great, I saw your code, the D3 function is awesome.

best,

yves

2016-02-14 14:28 GMT+00:00 Fabio Amaral <notifications@github.com>:

> Hello Yves,
>
> No problem, It was fun working on this dataset.
> I was already preparing an markdown document for this analysis and I will
> share it soon.
>
> Cheers
>
> Fabio
>
>

**Comment by YvesCR** [comment]
Any need of help for markdown, just shoot.

2016-02-14 15:22 GMT+00:00 Yves Crutain <yves.crutain@gmail.com>:

> Great, I saw your code, the D3 function is awesome.
>
> best,
>
> yves
>
> 2016-02-14 14:28 GMT+00:00 Fabio Amaral <notifications@github.com>:
>
>> Hello Yves,
>>
>> No problem, It was fun working on this dataset.
>> I was already preparing an markdown document for this analysis and I will
>> share it soon.
>>
>> Cheers
>>
>> Fabio
>>
>>

**Comment by Fredus14** [comment]
Hi Yves,

I’ve just sent a pull request to insert the rmarkdown and html documents. I could not find a way to embed de interactive visualisations in the document so I inserted a static figure as a link to the ones I had in my github.io <http://github.io/>. I wish I could find a way to render it all together. Any way, I have also pushed the the files for making the two interactive visualisations (LDAvis and stm-visualization) if they can be of any use.

I have seen just now the instructions from the link you provided. I am going to have a good look at it but will only have time by the middle of the week.
Let me know if what I sent is good enough for the purpose or you recommend some modification.

Best

Fabio

**Comment by YvesCR** [comment]
Hi Fabio, I know these stuffs may be time consuming so don't bother to
create a rmarkdown with the d3 visualisation inside(I'll try it, though,
for my personnal culture :) ).

I'll try to update the files tomorrow.



2016-02-14 22:38 GMT+00:00 Fabio Amaral <notifications@github.com>:

> Hi Yves,
>
> I’ve just sent a pull request to insert the rmarkdown and html documents.
> I could not find a way to embed de interactive visualisations in the
> document so I inserted a static figure as a link to the ones I had in my
> github.io <http://github.io/>. I wish I could find a way to render it all
> together. Any way, I have also pushed the the files for making the two
> interactive visualisations (LDAvis and stm-visualization) if they can be of
> any use.
>
> I have seen just now the instructions from the link you provided. I am
> going to have a good look at it but will only have time by the middle of
> the week.
> Let me know if what I sent is good enough for the purpose or you recommend
> some modification.
>
> Best
>
> Fabio
>
>

**Comment by Fredus14** [comment]
Hi Yves,

Please let me know if you figure out how to add the visualisation. I am a complete newbie in these and would be great to learn a bit.
I saw your link about how to create a blog from rmarkdown. I would love to have go at it and host my own blog sometime instead of having stuff loosely placed in rpub and github.io <http://github.io/>.

Cheers

Fabio

**Comment by YvesCR** [comment]
All is explained in the article. If you want some good link, you could look
at the ones at the end of my article on jekyll+github+rmarkdown, here:
http://data-laborer.eu/2015/12/Why_blogging_with_jekyll.html

But basically, you could dl the github repo of the blog or the original
github repo of Yihui Xie <https://github.com/yihui/knitr-jekyll> and build
your own site on these templates.


2016-02-15 17:19 GMT+00:00 Fabio Amaral <notifications@github.com>:

> Hi Yves,
>
> Please let me know if you figure out how to add the visualisation. I am a
> complete newbie in these and would be great to learn a bit.
> I saw your link about how to create a blog from rmarkdown. I would love to
> have go at it and host my own blog sometime instead of having stuff loosely
> placed in rpub and github.io <http://github.io/>.
>
> Cheers
>
> Fabio
>
>
>

**Comment by Fredus14** [comment]
Awesome! Its looks straightforward. Thank’s for sharing.

**Comment by svenski** [comment]
Yves- thanks for showing how to create a markdown - I think it's great.
However, I think we should just simply accept when we get pull requests
though, it can be quite a bit of work to put together a R-markdown if you
are not familiar with it (or using D3 here as you pointed out). My main
interest is that I would not like to discourage any participation in the
repo by enforcing an R-markdown, so I would prefer just to accept pull
requests as is. Does that make sense to you?

Fabio - thanks for contributing to the R-repo. Did you work on this during
the R-dojo, or did you create it afterwards? I think I remember you
mentioning this to me, but I thought it was something outside of the dojo.
Is that correct? No big deal, I don't think it's necessary wrong to include
it if it was generated outside, but maybe a link to to original git repo
where you had could be a better option IMHO. You can also link to any of
your code on the meetup site in a comment.

Thanks
Sergiusz

**Comment by Fredus14** [comment]
Hi Sergiusz,

I had done a similar analysis before using business reviews from Yelp website so I though to explore the emails dataset in a similar fashion. 
I could only do some part during the meeting and continued with it later at home. 

Sorry for deviating a bit from the main task idea. It was still beyond my current abilities but I interested to learn a bit from your idea of using MC for generating random emails. 
Please let me know when you post the code to the repo.

Cheers

Fabio

**Comment by YvesCR** [comment]
Hi guys,

yes, it overrun a little bit the concept of coding dojo. Let's keep it
simple.

The idea to use MC for the creation of new emails looks awesome, BTW.

@Fabio:

The script could go as well on the kaggle scripts of the Clinton
competition:
https://www.kaggle.com/kaggle/hillary-clinton-emails/scripts

And to be fair, this is where the script will be the most viewed. But here,
as well, it will take times to have it sorted.

Y

2016-02-15 18:24 GMT+00:00 Fabio Amaral <notifications@github.com>:

> Hi Sergiusz,
>
> I had done a similar analysis before using business reviews from Yelp
> website so I though to explore the emails dataset in a similar fashion.
> I could only do some part during the meeting and continued with it later
> at home.
>
> Sorry for deviating a bit from the main task idea. It was still beyond my
> current abilities but I interested to learn a bit from your idea of using
> MC for generating random emails.
> Please let me know when you post the code to the repo.
>
> Cheers
>
> Fabio
>
>
>

**Comment by Fredus14** [comment]
Yes, no problem. Good idea about posting it there. I was already thinking about it.
This week I will be working on a project deadline I have and probably next week I will invest some time to shape it in the form of a proper article with discussion and conclusions, etc.
Yves, please let me know if you find an easy way of embedding these D3 in the document...
Cheers
Fabio

**Comment by svenski** [comment]
Hey Fabio, I saw that you post a link to the analysis on the meetup page. I'll close this for now then.
Cheers
Sergiusz

**Comment by Fredus14** [comment]
Sure, no problem
Fabio

**Pull request closed without merging**
