### PR TITLE
voronoi files

### PR DESCRIPTION
**Pull request by YvesCR**
add the voronoi plot

### CODE REVIEW

**Comment by svenski** [comment]
Hi Yves

You have included some files like .Rhistory, .RData and also a full .Rprofile. Would you mind removing these and re-submitting the pull request? (Also, it could be worth to add them to .gitignore if you want to avoid adding these to git in the future).

Cheers
Sergiusz

**Comment by YvesCR** [comment]
Hi,

good move, the .gitignore.

I I published only the files this time.

Tell me if it's good.

best,

Y

2015-07-15 16:32 GMT+01:00 svenski <notifications@github.com>:

**Comment by svenski** [comment]
I still see them, but I realise it's for the June-2015 folder, not the july one. If you remove those, I'll merge the pull request.

Thanks
Sergiusz

**Comment by YvesCR** [comment]
I think I have deleted them, it should be good.

thanks,
yves

2015-07-15 17:02 GMT+01:00 svenski <notifications@github.com>:

**Pull request merged**
